[build]
  command = "npm run export"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Static site configuration (no Next.js plugin needed for static export)

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 